### ISSUE TITLE
求loss损失函数时，为什么用binary_crossentropy而不用softmax或sigmoid?

### ISSUE THREAD

**Issue by Flowingsun007** [calmisential/YOLOv3_TensorFlow2#8]
不是二分类，为什么需要用binary_crossentropy而不用softmax或sigmoid?不太明白望解答
![11](https://user-images.githubusercontent.com/28823622/77532572-19017400-6ed0-11ea-91db-9c46bd15349b.png)

**Comment by tianwangchn** [comment]
https://blog.csdn.net/leviopku/article/details/82660381 可以看看这里。

**Comment by Flowingsun007** [comment]
> https://blog.csdn.net/leviopku/article/details/82660381 可以看看这里。

好的，多谢指点
